# Generated by Django 6.0.5 on 2026-05-27 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('grupo', models.CharField(help_text='Grupos de A até L', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('GRUPO', 'Fase de Grupos'), ('R32', 'Dezesseis-avos (32 times)'), ('R16', 'Oitavas de Final'), ('QF', 'Quartas de Final'), ('SF', 'Semifinal'), ('TP', 'Disputa de 3º Lugar'), ('F', 'Final')], default='GRUPO', max_length=5)),
                ('data_hora', models.DateTimeField()),
                ('gols_casa', models.PositiveIntegerField(blank=True, null=True)),
                ('gols_fora', models.PositiveIntegerField(blank=True, null=True)),
                ('penaltis_casa', models.PositiveIntegerField(blank=True, null=True)),
                ('penaltis_fora', models.PositiveIntegerField(blank=True, null=True)),
                ('encerrado', models.BooleanField(default=False)),
                ('jogo_origem_casa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proximo_jogo_casa', to='core.jogo')),
                ('jogo_origem_fora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proximo_jogo_fora', to='core.jogo')),
                ('time_casa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jogos_casa', to='core.time')),
                ('time_fora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jogos_fora', to='core.time')),
            ],
        ),
    ]
